### ISSUE TITLE
[Command line reindex] Issue with custom field methods

### ISSUE THREAD

**Issue by bobylito** [algolia/AlgoliaSearchBundle#10]
When importing objects with some of the information retrievable only through custom methods, the content may or may not be imported.

Example of custom method : 

```php
   /**
    * @Algolia\Attribute
    */
   public function creatorName()
   {
       return $this->creator->getName();
   }
```

**Comment by maxiloc** [comment]
Quick fix done. We need to investigate to see if we can do it cleaner
