### ISSUE TITLE
Index Relations Symfony

### ISSUE THREAD

**Issue by sergiownd** [algolia/AlgoliaSearchBundle#101]
Hei, I'm trying to idex a relation on this way:
```

/**
     * @ORM\ManyToOne(targetEntity="Specialty", inversedBy="professionals")
     * @ORM\JoinColumn(name="specialty_id", referencedColumnName="id", onDelete="CASCADE")
     * @Algolia\Attribute
     */
    private $specialty; 
```

But when I run my  

> php app/console algolia:reindex

Im getting this error:
```

  [Algolia\AlgoliaSearchBundle\Exception\NotAnAlgoliaEntity]                                                                                           
  Tried to index `specialty` relation which is a `Proxies\__CG__\AppBundle\Entity\Specialty` instance, which is not recognized as an entity to index.
```

Any help?

**Comment by odecharette** [comment]
hi

You need to index your targetted entity : 'speciality' with an * @Algolia\Attribute on the column you want to get (for exemple : name)

then in you index professionals you'll have speciality.name = "azerty"

**Comment by julienbourdeau** [comment]
Thanks @odecharette!

I'm working on a new version (3.0) and I have not kept this behavior, you can now index relationship even if they're not searchable (or indexable) entities.

If you find time to try this new version, please let me know what you think of it :)
