### ISSUE TITLE
Exceptions in algolia code break our code

### ISSUE THREAD

**Issue by chriwup** [algolia/AlgoliaSearchBundle#13]
I'm currently having the following exception thrown from algoliasearch-client-php/src/AlgoliaSearch/Client.php:504: 
"AlgoliaSearch\AlgoliaException: Operations quota exceeded, change plan to get more Operations."

We are using a trial plan, it's quite possible I have reached my quota.

Though looking at the stack, this Client code was run by AlgoliaSearchDoctrineEventSubscriber.

This means that every time I use my database via doctrine and update an entity that is indexed in algolia, an exception can be raised by any part of this bundle code (AlgoliaException / \Exception ..). This is not acceptable: our server code will not work any more whenever an exception occurs.

Code in AlgoliaSearchDoctrineEventSubscriber should be within try / catch to avoid any exception bubbling up and breaking our code. I suggest you use the logger to write such exceptions in a log file.

**Comment by maxiloc** [comment]
@chriwup I am not sure catching the exception and putting it in the log should be directly included in the extension.

It would means that in case of bad credentials, curl not installed, quota exceeded, ..., you won't have any exception raised by the extension which not what we want.

The errors thrown by AlgoliaSearchDoctrineEventSubscriber occurs when you add/delete/update an object that is supposed to be sync by Algolia. I think it would be better to try catch for AlgoliaException in your own code if you want it to be safe for this kind of error.

What do you think ?

**Comment by chriwup** [comment]
Search is not a critical component for most companies, if syncing fails it is sad but it should in no way prevent the rest of the program from working correctly. For instance if the algolia api server is down (as it happens to all websites on this planet), I don't want it to bring down my server too.

If curl is not installed or bad credentials are given, I suppose the developer doing an Algolia integration will find out that things don't work and a little documentation should point them towards their log file.

You might also add an algolia configuration to let the user of the bundle choose the expected behaviour : catch exceptions and log them or leave them bubbling up.

**Comment by chriwup** [comment]
Side note: as we're dealing with a doctrine subscriber here, I see no way of catching exceptions thrown there on our side..

**Comment by maxiloc** [comment]
@chriwup Yes, the algolia configuration is a good idea (with error thrown by default).

Can you modify the pull request to handle it ?

**Comment by chriwup** [comment]
I have updated the pull request.

**Comment by maxiloc** [comment]
@chriwup Thanks a lot, I am gonna test it and merge it asap

**Comment by maxiloc** [comment]
Fixed with #14
