### ISSUE TITLE
Ability to change the default field for objectID

### ISSUE THREAD

**Issue by vvo** [algolia/AlgoliaSearchBundle#20]
The currently selected field for objectID is always the primary key, it could be useful to be able to provide another field for it.

**Comment by Nainterceptor** [comment]
Hi @vvo, my PR #34 is related to this issue.

**Comment by vvo** [comment]
Awesome! @maxiloc is on it and gave you feedback

**Comment by Nainterceptor** [comment]
If the PR close this issue, maybe you can send a voucher to @AdrenalineHunter =p

**Comment by maxiloc** [comment]
@Nainterceptor Thanks for contributing. We do not give voucher for github contribution. But feel free to send us your postal address via email so that we can send you some swag :smile:
