### ISSUE TITLE
Private properties in Indexer - can you make them protected?

### ISSUE THREAD

**Issue by mpclarkson** [algolia/AlgoliaSearchBundle#22]
Hi there

I need to implement a custom Indexer but I'm having some issues with private properties.

Specifically, is there any chance you could make the following properties in the `Indexer` clas `protected` rather than `private`, or perhaps type hint the listener service so it will accept an `IndexerInterface` rather than only the base class?

```php
 private $entitiesScheduledForCreation = array();
 private $entitiesScheduledForUpdate = array();
 private $entitiesScheduledForDeletion = array();
```

I can extend the class and inject extra dependencies to add additional data (e.g. CDN urls) without any problems, but I need to be able to access these properties to build a `master` index... unless there is some other way to do this?

Let me know if that's not clear...

**Comment by mpclarkson** [comment]
Basically, I am trying to override this method as follows but I can't access these private properties:

```php
public function processScheduledIndexChanges()
    {
        ///.... 
        //Duplicate each entity to build an aggregated index
        $aggregatedIndex = $this->makeEnvIndexName(self::AGGREGATED_INDEX, true);

        $makeAggregatedIndex = function($group) use ($aggregatedIndex) {
            $new = new ArrayCollection();
            foreach($group as $k => $v) {
                foreach($v as $object) {
                    if(!$new->contains($object)){
                        $new->add($object);
                    }
                }
            }

            if($new->count() > 0) {
                $group[$aggregatedIndex] = $new->toArray();
            }

            return $group;
        };

        $this->performBatchCreations($makeAggregatedIndex($creations));
        $this->performBatchUpdates($makeAggregatedIndex($updates));
        $this->performBatchDeletions($makeAggregatedIndex($deletions));

        $this->removeScheduledIndexChanges();
    }

```

**Comment by maxiloc** [comment]
@mpclarkson Just made them protected.

**Comment by maxiloc** [comment]
430e732806a89a00f9430afb45b2b24ba886374f is better :)

**Comment by mpclarkson** [comment]
Awesome thanks so much.
