### ISSUE TITLE
attributesForFaceting

### ISSUE THREAD

**Issue by mpclarkson** [algolia/AlgoliaSearchBundle#23]
Hi there

I don't believe the `attributesForFaceting` annotation is working. I have the following mapping but the facets are not created. The indices are populated fine other than the missing facets.

This is using Symfony 2.7.3.

```php
/**
 * Overall Index
 *
 * @ORM\Table(
 *  name="search_overall_index",
 *  indexes = {
 *         @ORM\Index(name="idx_search_class_identifier", columns={"class", "identifier"})
 *      },
 *  uniqueConstraints={
 *     @ORM\UniqueConstraint(columns={"class", "identifier"})
 *    }
 * )
 *
 * @UniqueEntity(fields={"class", "identifier"})
 *
 * @ORM\Entity(repositoryClass="SearchBundle\Repository\OverallRepository")
 * @ORM\HasLifecycleCallbacks
 *
 * @Algolia\Index(
 *     attributesForFaceting = {"type", "user", "project"},
 *     attributeForDistinct = "objectKey"
 * )
 *
 */
class Overall extends BaseEntity
{

  //Other properties and methods: Example mapping for type:

    /**
     * @var string
     *
     * @ORM\Column(name="type", type="string", length=255, nullable=false)
     * @Assert\NotBlank()
     * @Algolia\Attribute(algoliaName="type")
     */
    private $type;

```

**Comment by redox** [comment]
Hey @mpclarkson,

did you apply the settings with `php app/console algolia:settings --push` after adding this `attributesForFacetting` index setting (https://github.com/algolia/AlgoliaSearchBundle#index-settings) ?

**Comment by mpclarkson** [comment]
Oops, sorry I missed that.  Would be nice if it were automatic though - one less deployment step! 

Thanks for the prompt response.

**Comment by mpclarkson** [comment]
H

**Comment by mpclarkson** [comment]
Hi there

I'm having some problems running this command associated with constructors caused by line 148 in `vendor/algolia/algolia-search-bundle/Indexer/Indexer.php`

The bundle instantiates an entity here ` $entity = new $class();` but this throws an exception if the constructor requires arguments.  Until now, I've been able to get around this with our own entities by allowing null but this doesn't work for entities provided by third party bundles. For example:

```
Warning: Missing argument 1 for FOS\UserBundle\Model\Group::__construct(), called in /home/vagrant/Code/hilenium-application/vendor/algolia/algolia-search-bundle/Indexer/Indexer.php on lin  
  e 148 and defined 
```

**Comment by mpclarkson** [comment]
Changing this line to `$entity = $reflClass->newInstanceWithoutConstructor();` fixes the problem. I'll submit a PR if you want?

**Comment by redox** [comment]
thank you for the investigation. :) We've decided to not set the settings automatically because it's kind of complex to detect if we need to save them or not -> since PHP is stateless, we would need to check if the settings changed at each indexing.

Regarding the `newInstanceWithoutConstructor`, that's indeed a good idea. We would love to merge your PR!

**Comment by mpclarkson** [comment]
Cheers. PR submitted.
