### ISSUE TITLE
Reverse-Routing – Index Urls of entities

### ISSUE THREAD

**Issue by psren** [algolia/AlgoliaSearchBundle#25]
In the readme the ``url``is mentioned in the attributesToIndex

```
attributesToIndex = {"name", "description", "url"},
```

Is there any generator for reverse-routing a url?
I didn't find a way to do this and don't want to inject the container or something into my entities for that.

**Comment by maxiloc** [comment]
@psren No there is no way to do that automatically. You need to have a custom method method getUrl on your model and index it in Algolia
