### ISSUE TITLE
setSettings is never called on index creation

### ISSUE THREAD

**Issue by Nainterceptor** [algolia/AlgoliaSearchBundle#35]
Hello,

Use case : 

``` php
/**
 * Activity
 *
 * @ORM\Table()
 *
 * @Algolia\Index(
 *     attributesForFaceting = "locale"
 * )
 */
class Activity implements Translatable
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer", nullable=false)
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

 //Other things

    /**
     * @Algolia\Attribute
     * @Algolia\Id
     * Used locale to override Translation listener`s locale
     * this is not a mapped field of entity metadata, just a simple property
     */
    protected $locale;

//Getters & Setters
}
```

Expected : `app/console algolia:reindex --unsafe MyBundle:Activity` should trigger `\AlgoliaSearch\Index::setSettings` to persist `Algolia\Index` annotation

Current behavior : My entity is persisted but configuration mismatch. If I set a breakpoint on the `setSettings`, the function is never called. Is it normal ?

Regards,
Gaël

**Comment by Nainterceptor** [comment]
This work around do the trick but seems to be ugly. https://github.com/AdrenalineHunter/AlgoliaSearchBundle/compare/master...AdrenalineHunter:patch-issue-35

Not a solution, just a fix for my case, I don't have more time to allocate to this task, sorry for that.

**Comment by rayrutjes** [comment]
We will make sure this works as expected in V3. Flagging it.
