### ISSUE TITLE
Timeout config

### ISSUE THREAD

**Issue by tristanbes** [algolia/AlgoliaSearchBundle#38]
Hello,

Since our new hoster installed a dedicated firewall (stormpath), the algolia request is taking at least 6 seconds to accomplish (i don't know why)

Can you expose a global settings in the bundle to increase the timeout option of the php library undearneath please ( http://stackoverflow.com/questions/35693340/algolia-php-sdk-hosts-unreachable
) ?

``` php
Uncaught PHP Exception AlgoliaSearch\AlgoliaException: 
"Hosts unreachable: Resolving timed out after 2000 milliseconds,Resolving timed out after 2000 milliseconds,Resolving timed out after 4000 milliseconds,Resolving timed out after 4000 milliseconds" 
at vendor/algolia/algoliasearch-client-php/src/AlgoliaSearch/Client.php line 440 {"exception":"[object] (AlgoliaSearch\\AlgoliaException(code: 0): Hosts unreachable: Resolving timed out after 2000 milliseconds,Resolving timed out after 2000 milliseconds,Resolving timed out after 4000 milliseconds,Resolving timed out after 4000 milliseconds at //vendor/algolia/algoliasearch-client-php/src/AlgoliaSearch/Client.php:440)"} []
```

**Comment by redox** [comment]
Hi @tristanbes, could you tell us what is the version of the underlying `algoliasearch` API client that you're using? I know the Symfony bundles depends on `1.6.0` but just want to be sure we're not impacted by old cURL bugs we've fixed recently.

**Comment by tristanbes** [comment]
We're on 1.6.3.
Sysadmins fixed the firewall itself and now we're hitting you in a normal way ~1sec instead of 6. So having a timeout option as an global config for the bundle could be great, but it's not critical to us any longer ;-)

**Comment by redox** [comment]
> We're on 1.6.3.
> Sysadmins just fixed the firewall itself and now we're hitting you in a normal way ~1sec instead of 6. So having a timeout option as an global config for the bundle could be great, but it's not critical to us any longer ;-)

Alright, good to know :) We're gonna add it to the roadmap but if you want to submit a pull-request, I would be happy to merge it so we can move fast(er)!

**Comment by rayrutjes** [comment]
Closing this ;)

We could indeed let users easily choose a default timeout in the future.
I'm afraid it will lead to hiding infra problems though.
