### ISSUE TITLE
IndexIf ignored for related entities as attributes

### ISSUE THREAD

**Issue by sgilberg** [algolia/AlgoliaSearchBundle#39]
Hi, I'm not sure if this is a bug or if it's just a design that I need to work around:

I have an index on an entity A that has a OneToMany relationship with entity B. I put an @Algolia\Attribute annotation on that property, and in my entity B I put @Algolia\Attribute annotations on the fields that I wanted to include in A's index. Works great! The B entities are pulled in as an array of objects with only the attributes I wanted to include - excellent. (And with the help of the manual indexer I was able to make sure that changes to entity B were incorporated in A's index as well.)

Except - I put an @Algolia\IndexIf on one of my methods in entity B that seems to be ignored. I don't have (or want) an index explicitly on entity B, but I would like to pull into my A index only the B objects that meet a specific condition.

So my main question is, is this intended? Is there not a way to conditionally include OneToMany related entities if the @Algolia\Attribute tag is used on their property definition? If this is intended, my next move would be to include a custom method in A that returns only the B entities I want to conditionally include, and put the attribute tag there, but I thought I'd check first.

Also, as a general note, I think this bundle is really helpful, and I was relieved to find that I was able to include related entities as attributes - but I discovered that based on reading the previously submitted issue tickets. I think it would be great to note this capability in the README - thanks!

**Comment by maxiloc** [comment]
The bundle does handle this. It make sense for your use case and I guess this could be doable, but I am not sure we want do that by default (that would be a breaking change), let's keep this issue open, we'll see how we can improve that

**Comment by sgilberg** [comment]
Thanks @maxiloc - I can understand not wanting to do it by default, so I will work around it for now.
