### ISSUE TITLE
Config index fields wihtout annotations?

### ISSUE THREAD

**Issue by markitosgv** [algolia/AlgoliaSearchBundle#40]
Is possible to do that? Or is planned to implement that?

I've got some entities from a third part vendor, and i can't put annotations in there.

**Comment by maxiloc** [comment]
@markitosgv Sorry for the long delay. We are thinking about moving away from annotation, but it will require us to probably start from scratch (so it could some time). In the meantime, what you can do is use the php client directly to push your data

**Comment by rayrutjes** [comment]
Flagging this as part of V3, we definitely need to work on our levels of abstractions.
Thanks for reporting this in the first place.
