### ISSUE TITLE
Slaves config : facets on a slave indice

### ISSUE THREAD

**Issue by florentdestremau** [algolia/AlgoliaSearchBundle#41]
Hi,

I'm trying to understand how I can set facets on a slave indice. I have annotations like this:

```
/**
 * Event
 *
 * @ORM\Table(name="event")
 * @ORM\Entity(repositoryClass="AppBundle\Repository\EventRepository")
 * @ORM\HasLifecycleCallbacks
 * @Serializer\ExclusionPolicy("all")
 * @AppAssert\HasMorePlacesThanBookings()
 * @Algolia\Index(
 *     attributesForFaceting = {"macroCategoryTitle", "timeStamp"},
 *     ranking = {"asc(timeStamp)", "typo","geo","words","filters","proximity","attribute","exact","custom"},
 *     customRanking = {"asc(finalPrice)"},
 *     slaves = {"Event_dev_final_price_asc"}
 * )
 */
class Event
```

The problem is that the slave that  created does not have the same attributesForFaceting when I push the configuration so when I sort my results my facets widgets disapear :cry: 

Any idea how to make this work ?

Cheers

**Comment by florentdestremau** [comment]
Also i get an error `A slave index is already slave of another index` whenever i try to reindex after pushing my configuration to algolia, it's pretty annoying, what did I do wrong ?

**Comment by maxiloc** [comment]
The second issue is probably related to the env, the same slave name is probably used for two envs. I am currently investigating the first one

**Comment by maxiloc** [comment]
So the issue is, there is no set settings done on the slaves, we can fix that pretty easily but that would mean loosing the ability to customize independently the master and the slave.
Let's keep this issue open, we will probably need to introduce a new annotation

In the meantime the easier way to handle that would be to do a small php script on the side that handle the setSettings

**Comment by florentdestremau** [comment]
What I would expect maybe is being able to configure something like:

```
slaves = {
  attributesForFaceting = {"macroCategoryTitle", "timeStamp"},
  ranking = {"asc(timeStamp)", "typo","geo","words","filters","proximity","attribute","exact","custom"},
  customRanking = {"asc(finalPrice)"}
}
```

**Comment by maxiloc** [comment]
yes it's a bit more tricky than this because you could have two slaves with two differents set of settings but yes that's the idea

**Comment by jonasdk** [comment]
@maxiloc What is the conclusion here? Is it something that would need to be changed by Algolia or is it implementation/usage of the indexes that creates this issue?
Can you point me to an example of solution of what you talks about 

> a small php script on the side that handle the setSettings

**Comment by rayrutjes** [comment]
As @maxiloc explained this is tricky given the current design. We will make sure we allow this kind of use cases by better designing our different abstractions in V3. Labelling this issue to be sure we don't forget your use case. Please bear with us, and sorry about the delay.
