### ISSUE TITLE
Missing entries during a reindex

### ISSUE THREAD

**Issue by florentdestremau** [algolia/AlgoliaSearchBundle#51]
Hello guys,

I am having trouble with algolia while reindexing an entity. There are some entries missing !

Here is my IndexIf:

``` php
     /**
     * @Algolia\IndexIf
     * @return boolean
     */
    public function isAlgolia()
    {
        return $this->published && $this->occuringDate > new \DateTime();
    }
```

And here is my database state:

```
SELECT DISTINCT count(*) FROM event WHERE occuring_date > NOW() AND published = true ;
 count 
-------
  2561
(1 row)
```

And I have 1687 records on my algolia dashboard.

Now the reindex command used to work on smaller amounts of entries, but since we made a x3 it seems some are missing. Event stranger, if I make any operations on a missing entity, it appears back in the indexes, so The IndexIf doesn't seem to be the matter.

I run a free plan, so I wonder if this could have any link ?

I will update this issue if I find a pattern between the events that are missing as currently it seems to be completely random.

**Comment by rayrutjes** [comment]
Hey @florentdestremau ,

Are you sure the `published` and `occuringDate` have the correct values when indexing at first? Could you log that to make sure?

Also, I would log all calls to isAlgolia and try to correlate that with the missing records.

To finish, we only have soft limits in Algolia so no problem there.

**Comment by florentdestremau** [comment]
Yes they are well defined because other than that the events are fully functional on the rest of the website.

Update: I imported my production database and in local environment the first reindex worked fine with all events synced, but a reindex over it gave the exact same amount of events.

Starting to see a pattern but not quite sure about the reason.

Tried deleting completely the index and reindexing and stuck on 1673... Wonder if it's not a conflict with previous entries...?

I'm trying to log the calls.

**Comment by rayrutjes** [comment]
Please also check that you check out your php logs.

**Comment by florentdestremau** [comment]
Not sure how to monitor useful information...

**Comment by florentdestremau** [comment]
Solved it by indexing manually. No idea why it didn't work though..

```
$em = $this->getContainer()->get('doctrine.orm.entity_manager');
        $eventRepository = $em->getRepository('AppBundle:Event');

        $qb = $eventRepository->createQueryBuilder('event')
            ->where('event.published = true')
            ->andWhere('event.occuringEndDate < :now')
            ->setParameter('now', new \DateTime())
            ->andWhere('event.occuringEndDate > :yesterday')
            ->setParameter('yesterday', new \DateTime('-1 day'));

        $events = $qb->getQuery()->getResult();
        $indexer = $this->getContainer()->get('algolia.indexer')->getManualIndexer($em);

        $count = $indexer->unIndex($events);
```

**Comment by rayrutjes** [comment]
Closing this @florentdestremau . Feel free to re-open if you have more context. Thanks for reporting it in the first place.

**Comment by florentdestremau** [comment]
@rayrutjes ok, a friend of mine told me it could be a network latency when dealing with large amounts of requests...anyway I don't use the reindex now, I index / unindex manually the events that are not published anymore, much better and cheaper in terms of queries :)
