### ISSUE TITLE
Support Inheritance and Doctrine Mapped  Superclasses ?

### ISSUE THREAD

**Issue by Agathver** [algolia/AlgoliaSearchBundle#56]
We have a entity structure with Single Table Inheritance and Doctrine mapped superclasses. However, indexing of properties in such a scenario appears to be not supported. 

Are we  doing anything wrong or are such configurations not supported ?

Here is an example of our entities

``` php
/**
 * Post
 * @ORM\Entity()
 * @ORM\InheritanceType("SINGLE_TABLE")
 * @ORM\DiscriminatorColumn(name="type", length=10)
 * @ORM\DiscriminatorMap({"question"="Question", "answer"="Answer"})
 */
abstract class Post
{
    /**
     * @var string
     *
     * @ORM\Column(name="title", type="string", length=255, nullable=true)
     * @Algolia\Attribute
     */
    protected $title;
    //...
}
```

``` php
/**
 * Answer
 * 
 * @ORM\Entity()
 */
class Answer extends Post
{
    /**
     * @var bool
     * @ORM\Column(name="votes", type="integer")
     * @Algolia\Attribute
     */
    public $votes;
   //...
}
```

Expected: Index for Answer should contain the field `title` too

**Comment by julienbourdeau** [comment]
Hi @Agathver,

I had a look and indeed the entities are not indexed, although the index is created. I'll work on that.

Thank you for opening an issue.

**Comment by julienbourdeau** [comment]
Hi @Agathver,

I gave it another shot and I got it to work! I think your problem is because you are setting title to `protected`. You need to either have:

* public properties
* public getter/setter

Can you try again and see if you get it too work as expected?
