### ISSUE TITLE
Create new tag for fixes

### ISSUE THREAD

**Issue by mrardon** [algolia/AlgoliaSearchBundle#6]
Looks like this is fixed in d7ed4d2bdc740cdc5380b2ea9dc0cdf1b31e4e37 but all the tagged versions, 1.0.0 and 1.0.1 have this issue and was blowing things up for me. Anyway we can get a 1.0.2 tag release that includes this fix. Thanks.

**Comment by maxiloc** [comment]
@mrardon I released 1.0.2 today.
