### ISSUE TITLE
Class AlgoliaSearchEventSubscriber not found

### ISSUE THREAD

**Issue by brunonic** [algolia/AlgoliaSearchBundle#7]
hi, I just setup this bundle but got this error :

PHP Fatal error:  Class 'Algolia\AlgoliaSearchBundle\EventListener\AlgoliaSearchEventSubscriber' not found

Any idea ?

**Comment by maxiloc** [comment]
Yes it was fixed with https://github.com/algolia/AlgoliaSearchBundle/commit/d7ed4d2bdc740cdc5380b2ea9dc0cdf1b31e4e37
We didn't create a new release so it wasn't available through composer.

It should be good now
