### ISSUE TITLE
Update attribute namings

### ISSUE THREAD

**Issue by rayrutjes** [algolia/AlgoliaSearchBundle#85]
- `attributesToIndex` -> `searchableAttributes`
- `numericalAttributesToIndex` -> `numericAttributesForFiltering`

**Comment by seafoox** [comment]
Once done, please update 
```php
/**
 *
 * @ORMEntity
 *
 * @AlgoliaIndex(
 *     attributesToIndex = {"show_name", "episode_name", "episode_of"}
 * )
 *
 */
class TVShow
{
}
``` 
in the Guide about data formating, located at 
`guides/indexing/2-formatting-your-data.html.md.erb`
