### ISSUE TITLE
Order Annotation maters for perEnvironment indexation

### ISSUE THREAD

**Issue by bourdeau** [algolia/AlgoliaSearchBundle#89]
Hello,

```
 * @Algolia\Index(autoIndex=true)
 * @Algolia\Index(perEnvironment=false)
```
=> Works as expected

```
* @Algolia\Index(perEnvironment=false)
* @Algolia\Index(autoIndex=true)
```
=> Ignore perEnvironment=false

Is it normal ?

**Comment by rayrutjes** [comment]
Not expected ;)

Could this somehow be related to local caching of entity metas on your side?

Otherwise, if you find the main reason, I'd gladly accept a PR 👍

**Comment by rayrutjes** [comment]
Hey @bourdeau 

i've been unable to re-produce this, closing it for now.
Feel free to give us more context to re-produce it.
