### ISSUE TITLE
Boolean value after form submit

### ISSUE THREAD

**Issue by brunonic** [algolia/AlgoliaSearchBundle#91]
There is a difference between two case for a boolean value.
I have a simple symfony form for create and edit a BlogPost entity.

My form
```php
    ->add(
        'visible',
        ChoiceType::class,
        [
                'label' => 'Etat',
                'choices' => [
                        false => 'Brouillon',
                        true => 'En ligne'
                ]
        ]
    )
```

My entity
```php
    /**
     * @var bool
     *
     * @ORM\Column(name="visible", type="boolean")
     *
     * @Algolia\Attribute
     */
    private $visible;
```

And now this my index. On the top, the result of the index after form submit. On the bottom, the result after a algolia:reindex command.

![screen shot 2017-01-20 at 07 12 13](https://cloud.githubusercontent.com/assets/1011840/22145243/c9ddd15a-df00-11e6-84fc-b321c9e39c0d.jpg)

Facet can't be used for visible:true

**Comment by rayrutjes** [comment]
Hi @brunonic 
I was informed of your issue internally, thanks for taking the time to actually submit an issue here.

In the end, my first conclusion would be that the casting of the values only takes place when retrieving the values from the database. 

Currently, we do listen for the flush event and act upon that and in that case, the cast didn't take place yet.

I will investigate this and see if we can better handle this to be more consistent.
A quick win for you would be to store your boolean values as integers (0/1) but that would force you to do the casting yourself when using the values each time unless you use non-strict equalities in your codebase.

Give me some time to look into this ;)

**Comment by rayrutjes** [comment]
Hey @brunonic , so the thing is that we send the entity in the state it is in just before being sent to the database. My guess is that your form actually sets `1` or `0` for the `visibility` property.

When re-indexing everything though, the results are being fetched from the database and casted to the correct type.

To enforce the boolean, here is what I suggest you add to your entity:

```php
/**
     * Set visible
     *
     * @param boolean $visible
     *
     * @return Product
     */
    public function setVisible($visible)
    {
        $this->visible = (bool) $visible;

        return $this;
    }
```
