### ISSUE TITLE
Replicas index name does not support index_name_prefix and Symfony env

### ISSUE THREAD

**Issue by KevinDumont** [algolia/AlgoliaSearchBundle#92]
Hi all,

The bundle does not seem to use index_name_prefix and Symfony env to create replicas index name.
Ex: Class Product
Main index name will be [index_name_prefix]\_Products\_[symfony_env] but there is no way to do the same with replicas

**Comment by julienbourdeau** [comment]
Hi @KevinDumont,

Have you found a workaround for this issue? I'm looking at it but with the current design it's not very straight forward.

Unless I missed something I don't think you can set the replica settings with the annotation. Maybe we should introduce something like this and introduce the per environment name at the same time.

```php
/*
 * @Algolia\Index(
 *     customRanking = {"desc(popularity)", "asc(name)" },
 * )
 *
 * @Algolia\Replica({
 *     "name"="replica_name",
 *     "ranking"={"desc(price)", "typo", "geo", "words", "proximity", "attribute", "exact", "custom"}
 * })
 *
 */
```

What do you think?

**Comment by KevinDumont** [comment]
Hi @julienbourdeau 

Yes you are right, we can't set replica settings with annotation.
Don't forget we can have several replicas, maybe we can have something like this

```php
 * @Algolia\Replica({
 *     "name"="replica_name_1",
 *     "ranking"={"desc(price)", "typo", "geo", "words", "proximity", "attribute", "exact", "custom"}
 * },{
 *     "name"="replica_name_2",
 *     "ranking"={"desc(price)", "typo", "geo", "words", "proximity", "attribute", "exact", "custom"}
 * })
```

But what about people who already use the current annotation ?
```php
 * @Algolia\Index(
 *     replicas = {
 *         "replica_name_1",
 *         "replica_name_2"
 *     }
 * )
```

**Comment by julienbourdeau** [comment]
Thanks for your inputs. In the end, I'm working a new version of the bundle and it won't have this type of feature. I won't be adding this to the 2.0 version.

I believe it's best if settings are managed in the dashboard or in a json file in your project (upcoming feature on 3.0). This is the only way to ensure that 100% of the Algolia features are available.
