### ISSUE TITLE
We are not able to set the sorting of replicas in annotation

### ISSUE THREAD

**Issue by maxiloc** [algolia/AlgoliaSearchBundle#93]

**Comment by rayrutjes** [comment]
Could you give more details so that I can implement something?

**Comment by maxiloc** [comment]
We need to be able to do the same thing than in laravel.
https://github.com/algolia/algoliasearch-laravel#primaryreplica

1) Set the replicas settings for the index. We handle that already
2) Being able to set the replica settings. If I am not wrong, we don't handle that

**Comment by julienbourdeau** [comment]
The new version of the bundle won't be offering this kind of features. I think it's better if settings are handled in a json file or in the dashboard. It won't be added to the 2.x version either.
